/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Keyboard.java
 *
 * Created on May 14, 2013, 9:02:13 AM
 */
package com.hkt.client.swingexp.app.virtualkey.number;

import java.awt.GridLayout;

import javax.swing.JTextField;

/**
 *
 * @author Administrator
 */

public class Keypad extends javax.swing.JDialog  {

    private PanelKeypadLong panel;

    public Keypad() {
        initComponents();
        this.setModalExclusionType(ModalExclusionType.APPLICATION_EXCLUDE);
        this.setAlwaysOnTop(true);
        this.setLayout(new GridLayout());
        panel = new PanelKeypadLong();
        this.add(panel);
//        btn0.setBorder(new RoundedBorder(20));
//        btn1.setBorder(new RoundedBorder(20));
        // setModal(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 871, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 141, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
    this.setVisible(false);
}//GEN-LAST:event_formWindowLostFocus

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
   
    public void setIndex(int index) {
        panel.setIndex(index);
    }

    
    public void setTextField(JTextField textField) {
        panel.setTextField(textField);
    }

    
    public void setToolTip(String toolTipText) {
        panel.setToolTip(toolTipText);
    }

    
    public void setShowAll(boolean flag) {
        panel.setShowAll(flag);
    }

    
    public void setShowSale(boolean flag) {
        panel.setShowSale(flag);
    }

    
    public boolean isShowAll() {
        return panel.isShowAll();
    }

    
    public boolean isShowSale() {
        return panel.isShowSale();
    }

    
    public void loadKeyboard() {
        panel.loadKeyboard();
    }
}
