/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelTextKeyboard.java
 *
 * Created on Jul 25, 2013, 2:40:37 PM
 */
package com.hkt.client.swingexp.app.virtualkey.text;

import java.awt.Component;
import java.awt.Dimension;
import java.awt.GridLayout;

import javax.swing.JComponent;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author longnt
 */
public class PanelTextKeyboard extends javax.swing.JPanel {

    /** Creates new form PanelTextKeyboard */
    private PanelKeyboardForPanel panelKeyboard;

    public PanelTextKeyboard() {
        initComponents();
        setOpaque(false);
        this.setLayout(new GridLayout());
        panelKeyboard = new PanelKeyboardForPanel();
       
        this.add((JPanel) panelKeyboard);
        panelKeyboard.setPreferredSizePanel(this);
        panelKeyboard.setTypeKeyboard(1);
        setPreferredSize(new Dimension(700, 208));
    }

    public void setText(JComponent textField) {
        if (panelKeyboard != null) {
            if (textField instanceof JTextField) {
                panelKeyboard.setTextField((JTextField) textField);
            } else if (textField instanceof JTextArea) {
                panelKeyboard.setTextAria((JTextArea) textField);
            } else if (textField instanceof JTable) {                
                panelKeyboard.setTable((JTable) textField, ((JTable) textField).getSelectedRow());
            }
        }
    }

    public void setBackground(boolean flagBackground) {
        if (panelKeyboard != null) {
            panelKeyboard.setBackground(flagBackground);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(641, 230));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 641, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    /**Set trạng thái hiển thị của bàn phím ảo*/
    public void setStatusKeyboard(boolean status) {
        if (panelKeyboard != null) {
            panelKeyboard.setStatusKeyboard(status);
        }
    }

    public boolean getFlagShowAll() {
        return panelKeyboard.getFlagShowAll();
    }

    public boolean getFlagShowSale() {
        return panelKeyboard.getFlagShowSale();
    }
}
