/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TextKeyboard.java
 *
 * Created on Jul 2, 2013, 10:40:22 AM
 */
package com.hkt.client.swingexp.app.virtualkey.text;


import java.awt.GridLayout;

import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;


/**
 *
 * @author Zero
 */
public class TextKeyboard extends javax.swing.JDialog {

    private PanelKeyboardForDialog panelKeyboard;

    /** Creates new form TextKeyboard */
    public TextKeyboard() {
      setUndecorated(true);
        initComponents();
        this.setModalExclusionType(ModalExclusionType.APPLICATION_EXCLUDE);
        this.setAlwaysOnTop(true);
        this.setLayout(new GridLayout());
        panelKeyboard = new PanelKeyboardForDialog();
        this.add(panelKeyboard);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 686, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 307, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
    panelKeyboard.close();
    this.dispose();
}//GEN-LAST:event_formWindowLostFocus

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
   
    public void setTypeKeyboard(int typeKeyboard) {
        panelKeyboard.setTypeKeyboard(typeKeyboard);
    }

   
    public void setTextField(JTextField textField) {
        panelKeyboard.setTextField(textField);
    }

   
    public void setTextAria(JTextArea jTextArea) {
        panelKeyboard.setTextAria(jTextArea);
    }

   
    public void setIndex(int index) {
        panelKeyboard.setIndex(index);
    }

   
    public void setToolTip(String toolTipText) {
        panelKeyboard.setToolTip(toolTipText);
    }

   
    public void setShowAll(boolean flag) {
        panelKeyboard.setShowAll(flag);
    }

   
    public void setShowSale(boolean flag) {
        panelKeyboard.setShowSale(flag);
    }

   
    public boolean isShowAll() {
        return panelKeyboard.isShowAll();
    }

   
    public boolean isShowSale() {
        return panelKeyboard.isShowSale();
    }

   
    public void loadKeyboard() {
        panelKeyboard.loadKeyboard();
    }

   
    public void setTable(JTable jTable, int rowSelected) {
        panelKeyboard.setTable(jTable, rowSelected);
    }

   
    public void setBackground(boolean flagBackground) {
        panelKeyboard.setBackground(flagBackground);
    }
}
