package com.hkt.client.swingexp.app.core;

import java.awt.Image;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

import javax.swing.ImageIcon;

import com.hkt.client.swingexp.app.component.PanelBackgroundNotice;
import com.hkt.client.swingexp.app.component.PanelTrans;
import com.hkt.client.swingexp.homescreen.HomeScreen;

public class DialogNotice extends javax.swing.JDialog {
  /**
   * Creates new form DialogNotice
   */
  private static DialogNotice dialogNotice;

  public static DialogNotice getInstace() {
    if (dialogNotice == null) {
      dialogNotice = new DialogNotice();
    }
    return dialogNotice;
  }


  public DialogNotice() {
	  ImageIcon icon = new ImageIcon(HomeScreen.class.getResource("icon/icon.png"));
	  Image im = icon.getImage();
	  setIconImage(im);
    initComponents();
    this.dispose();
    this.setUndecorated(true);
    setLocationRelativeTo(this);
    setModal(true);

    addWindowListener(new WindowAdapter() {
      @Override
      public void windowOpened(WindowEvent e) {
      }
      
      @Override
      public void windowActivated(WindowEvent e) {
        Thread t = new Thread() {
          @Override
          public void run() {
              try {
                Thread.sleep(500);
                dispose();
              } catch (Exception ex) {
              	ex.printStackTrace();
              }
          }
        };
        t.start();
      }
      
      @Override
      public void windowStateChanged(WindowEvent e) {
        super.windowStateChanged(e);
      }
    });
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">
  private void initComponents() {

    panelBackground1 = new PanelBackgroundNotice();
    panelBackgroundResto1 = new PanelTrans();
    jLabel1 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    panelBackgroundResto1.setOpaque(false);

    jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("Thành công"); // NOI18N
    jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

    javax.swing.GroupLayout panelBackgroundResto1Layout = new javax.swing.GroupLayout(panelBackgroundResto1);
    panelBackgroundResto1.setLayout(panelBackgroundResto1Layout);
    panelBackgroundResto1Layout.setHorizontalGroup(panelBackgroundResto1Layout.createParallelGroup(
        javax.swing.GroupLayout.Alignment.LEADING).addGroup(
        javax.swing.GroupLayout.Alignment.TRAILING,
        panelBackgroundResto1Layout.createSequentialGroup().addContainerGap(18, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)));
    panelBackgroundResto1Layout.setVerticalGroup(panelBackgroundResto1Layout.createParallelGroup(
        javax.swing.GroupLayout.Alignment.LEADING).addGroup(
        panelBackgroundResto1Layout.createSequentialGroup().addGap(29, 29, 29)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

    javax.swing.GroupLayout panelBackground1Layout = new javax.swing.GroupLayout(panelBackground1);
    panelBackground1.setLayout(panelBackground1Layout);
    panelBackground1Layout.setHorizontalGroup(panelBackground1Layout.createParallelGroup(
        javax.swing.GroupLayout.Alignment.LEADING).addComponent(panelBackgroundResto1,
        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
    panelBackground1Layout.setVerticalGroup(panelBackground1Layout.createParallelGroup(
        javax.swing.GroupLayout.Alignment.LEADING).addGroup(
        javax.swing.GroupLayout.Alignment.TRAILING,
        panelBackground1Layout
            .createSequentialGroup()
            .addContainerGap()
            .addComponent(panelBackgroundResto1, javax.swing.GroupLayout.DEFAULT_SIZE,
                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addContainerGap()));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
        panelBackground1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE,
        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
    layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
        panelBackground1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

    pack();
  }// </editor-fold>
   // Variables declaration - do not modify

  private javax.swing.JLabel jLabel1;
  private PanelBackgroundNotice panelBackground1;
  private PanelTrans panelBackgroundResto1;
  // End of variables declaration
}
